- name: copy grafana servce bin 
  copy:
    src: "{{local_bin}}/{{ item }}"
    dest: /tmp/
    mode: '0755'
  with_items: 
    - grafana-9.1.7-1.x86_64.rpm

- name: install grafana service
  package:
    name: /tmp/grafana-9.1.7-1.x86_64.rpm
    state: present

- name: create grafana dashboard dir 
  file: 
    path: "/var/lib/grafana/dashboards"
    state: directory
    owner: grafana
    group: grafana

- name: "Grafana configuration file copy"
  template:
    src: "grafana.conf.j2"
    dest: /etc/grafana/grafana.ini
  notify: event_restart_grafana

- name: "Grafana server started"
  service:
    name: grafana-server
    enabled: true
    state: started

- name: "Check if Grafana is accessible."
  uri:
    url: http://127.0.0.1:3000
    method: GET
    status_code: 200