# - name: test 
#   debug:
#     msg: "{{ data_path }}"

- name: 安装 grafana
  yum: name=grafana state=latest enablerepo="tea"


# - name: 配置 granfana
#   template: src={{ item.src }} dest={{ item.dest }} mode=0644
#   with_items: 
#     - { src: prometheus.env.j2 , dest: /etc/default/prometheus}
#     - { src: prometheus.yml.j2 , dest: /etc/prometheus/prometheus.yml}
#   notify: restart prometheus

- name: 启动 grafana
  service: name=grafana-server state=started enabled=yes daemon_reload=yes

- name: 等待 grafana 服务启动成功
  wait_for: host=127.0.0.1 port=3000 state=started 
