---
- name: set org tea
  shell: |
    curl -u '{{ grafana_admin_username }}:{{ grafana_admin_password }}' -H 'Content-Type: application/json'  -X PUT  http://127.0.0.1:3000/api/org/1  -d '{"name": "tea"}'

- name: add datasource prometheus 
  shell: | 
    curl -u '{{ grafana_admin_username }}:{{ grafana_admin_password }}' -H 'Content-Type: application/json'  -X POST  http://127.0.0.1:3000/api/datasources -d  '{ 
    "name": "Prometheus",
    "type": "prometheus",
    "typeName": "Prometheus",
    "typeLogoUrl": "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg",
    "access": "proxy",
    "url": "http://127.0.0.1:9090",
    "user": "",
    "database": "",
    "basicAuth": false,
    "isDefault": true,
    "jsonData": {
      "httpMethod": "POST"
    },
    "readOnly": false
    }'

#--------------------------------------------------------------#
# Copy base dashboards (home dashboard & core application)
#--------------------------------------------------------------#
- name: Sync grafana home and core dashboards
  tags: [ always ]
  copy:
    src: dashboards/
    dest: /var/lib/grafana/dashboards/
    owner: grafana
    group: grafana
  with_items: 
    - grafana.py

- name:  Sync grafana dashboard against service
  tags: [ monitor ]
  copy:
    dest: /var/lib/grafana/dashboards/
    src: dashboards/{{ item }}
    owner: grafana
    group: grafana
  with_items: "{{ dashboard_json_files }}"

#--------------------------------------------------------------#
# Provisioning
#--------------------------------------------------------------#
- name: Provisioning grafana with grafana.py
  tags: [ monitor, dashboard_init ]
  ignore_errors: true
  shell: |
    #!/bin/bash

    # grafana access info
    export GRAFANA_ENDPOINT="http://127.0.0.1:3000"
    export GRAFANA_USERNAME={{ grafana_admin_username }}
    export GRAFANA_PASSWORD={{ grafana_admin_password }}

    # run provisinoing logic
    /var/lib/grafana/dashboards/grafana.py init /var/lib/grafana/dashboards
    # mv /var/lib/grafana/dashboards/*.json /var/lib/grafana/dashboards/*.json.1
...