- name: install repmgr
  package:
    name: repmgr{{PG_VERSION}}.x86_64
    state: present
  tags: repmgr

- name: postgres sudo privates
  copy:
    dest: /etc/sudoers.d/postgres
    content: | 
      Defaults:postgres !requiretty
      postgres ALL = NOPASSWD: /usr/bin/systemctl stop postgresql-{{PG_VERSION}}, \
      /usr/bin/systemctl start postgresql-{{PG_VERSION}}, \
      /usr/bin/systemctl restart postgresql-{{PG_VERSION}}, \
      /usr/bin/systemctl reload postgresql-{{PG_VERSION}}
    mode: 0400

- name: delete temp ssh keys
  file: 
    name: /tmp/{{ item }}
    state: absent
  with_items: 
    - id_rsa
    - id_rsa.pub
    - authorized_keys

#   command : echo -e 'y\n'|ssh-keygen -q -t dsa -f ~/.ssh/id_dsa -C "" -N ""
#   command : echo -e 'y\n'|ssh-keygen -q -t ecdsa -f ~/.ssh/id_ecdsa -C "" -N ""
- name: Generate ssh RSA host key
  shell : | 
   echo -e 'y\n'|ssh-keygen -q -t rsa -f /tmp/id_rsa -C "" -N ""
   cat  /tmp/id_rsa.pub >> /tmp/authorized_keys
   chmod 666 /tmp/id_rsa
   chmod 666 /tmp/id_rsa.pub
   chmod 666 /tmp/authorized_keys
  delegate_to: localhost

- name: set repmgr_ssh_key
  become_user: postgres
  copy: 
    dest: "~/.ssh/{{ item }}"
    src: /tmp/{{ item }}
    mode: 0600
  with_items: 
    - id_rsa
    - id_rsa.pub
    - authorized_keys

- name: delete temp ssh keys
  file: 
    name: /tmp/{{ item }}
    state: absent
  with_items: 
    - id_rsa
    - id_rsa.pub
    - authorized_keys

- name: collect ssh fingerprints
  become_user: postgres
  shell: >
    ssh-keyscan
    {% for host in groups['postgresql'] %}
    {{ host }}
    {% endfor %}
  register: __ssh_fingerprints

- name: ssh known_hosts
  become_user: postgres
  lineinfile:
    dest: ~/.ssh/known_hosts
    create: yes
    owner: "postgres"
    group: "postgres"
    mode: 0600
    line: "{{ item }}"
  with_items: "{{ __ssh_fingerprints.stdout_lines }}"
  
- name: postgres sudo privates
  copy:
    dest: /etc/sudoers.d/postgres
    content: | 
      Defaults:postgres !requiretty
      postgres ALL = NOPASSWD: /usr/bin/systemctl stop postgresql-{{PG_VERSION}}, \
      /usr/bin/systemctl start postgresql-{{PG_VERSION}}, \
      /usr/bin/systemctl restart postgresql-{{PG_VERSION}}, \
      /usr/bin/systemctl reload postgresql-{{PG_VERSION}}
    mode: 0400