- name: install etcd server 
  yum: 
    name: "etcd"
    state: "latest"
    enablerepo: "tea"
  tags: install
  
# TODO 二进制文件方式安装

- name: create data directory
  file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    group: etcd
  with_items: 
    - "{{ ECTD_CERT_DIR }}"
    - "{{ ETCD_WAL_DIR }}"