- include_tasks: 
    file: tuning.yml
    apply:
      tags: tuning
  tags: always

- include_tasks: 
    file: "install.yml"
    apply:
        tags: install
  tags: always

- include_tasks: 
    file: "sidekick.yml"
    apply:
      tags: sidekick
  tags: always