---
  - hosts: minio
    roles:
    - { role: os_base, server: minio }
    - { role: minio, playbook_action: "create"} 

  - hosts: monitor
    gather_facts: false
    tasks:
      #####################################################
      ## prometheus job config
      #####################################################
      - name: config prometheus file
        shell: | 
          result=$(cat /etc/prometheus/prometheus.yml | grep minio-job)
          if [[ "$result" == "" ]]
          then
            echo " # add minio job "  >> /etc/prometheus/prometheus.yml 
            cat /tmp/minio_job_{{ groups['minio'][0] }}_{{ groups['minio'][-1] }}.yml >> /etc/prometheus/prometheus.yml 
          fi
         
        tags: monitor
        #  rm /tmp/minio_job_{{ groups['minio'][0] }}_{{ groups['minio'][-1] }}.yml
      # - name: check prometheus config is ok
      #   shell: 
      #     promtool check config prometheus.yml
      #   tags: monitor

      - name: restart prometheus
        systemd: name=prometheus state=restarted enabled=yes daemon_reload=yes
        tags: monitor
      
      - name: "Check if prometheus is accessible."
        uri:
          url: http://127.0.0.1:9090
          method: GET
          status_code: 200
        tags: monitor
      #####################################################
      ## load grafana dashboard
      #####################################################
      - name: Provisioning grafana with grafana.py
        tags: [ monitor, dashboard_init ]
        ignore_errors: true
        shell: |
          #!/bin/bash

          # grafana access info
          export GRAFANA_ENDPOINT="http://127.0.0.1:3000"
          export GRAFANA_USERNAME={{ grafana_admin_username }}
          export GRAFANA_PASSWORD={{ grafana_admin_password }}

          # run provisinoing logic
          python /var/lib/grafana/dashboards/grafana.py load /var/lib/grafana/dashboards
    
      #####################################################
      ## 做一些清理工作. 为什么删除minio/.json ? 避免在load其他任务的时候重复load minio/.json
      #####################################################
      - name:  Delete grafana dashboard against service
        # tags: [ monitor ]
        file:
          path: /var/lib/grafana/dashboards/{{ item }}
          state: absent
        with_items: 
          - "minio"
...